### ISSUE TITLE
Apply Only on mobs

### ISSUE THREAD

**Issue by arochut** [duplxey/BlockEffects#3]
Even with permission settings set, mobs trigger effects when walking on blocks

**Comment by duplxey** [comment]
WALK and WALK_INSIDE are triggered on PlayerMoveEvent so that makes no sense that mobs would trigger block effects. I also tested the permissions and everything seems to work just fine.

**Comment by arochut** [comment]
Yeah, that was weird, maybe that was my server that was lagging, i actually have another issue, but i let you delete this thread and i'll do another :) Thanks for answering this quick tho !
